trigger: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: java-app-ci
      trigger:
        branches:
          include:
            - azure-pipelines-ci

variables:
  - group: ci-pipeline-vars
  - name: IMAGE_TAG
    value: "226"   # or use $[ resources.pipeline.ciPipeline.runID ]
  - name: IMAGE_URI
    value: "$(LOCATION)-docker.pkg.dev/$(PROJECT_ID)/$(REPOSITORY)/$(IMAGE_NAME):$(IMAGE_TAG)"
  - name: K8S_NAMESPACE
    value: "default"

stages:
  - stage: GCP_DEPLOY
    displayName: "Authenticate & Deploy to GKE"
    jobs:
      - job: Deploy
        displayName: "Deploy image $(IMAGE_URI) to GKE"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self

          # -----------------------------
          # INSTALL GCLOUD + AUTH PLUGIN
          # -----------------------------
          - task: Bash@3
            displayName: "Install gcloud & GKE Auth Plugin"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                echo "Installing gcloud CLI and GKE auth plugin..."
                sudo apt-get update -y
                sudo apt-get install -y apt-transport-https ca-certificates gnupg curl lsb-release
                echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
                curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
                sudo apt-get update -y
                sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin
                echo "Installed: $(gcloud version | head -n1)"
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True

          # -----------------------------
          # AUTHENTICATE GCP
          # -----------------------------
          - task: DownloadSecureFile@1
            name: DownloadGcpKey
            displayName: "Download GCP Service Account Key"
            inputs:
              secureFile: "$(SERVICE_ACCOUNT_SECUREFILE)"

          - task: Bash@3
            displayName: "Authenticate with GCP and Configure Docker"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                echo "Authenticating service account..."
                gcloud auth activate-service-account --key-file="$(DownloadGcpKey.secureFilePath)"
                gcloud config set project $(PROJECT_ID)
                gcloud auth configure-docker $(LOCATION)-docker.pkg.dev --quiet
                echo "Auth successful for $(PROJECT_ID)"

          # -----------------------------
          # GET GKE CLUSTER CREDENTIALS
          # -----------------------------
          - task: Bash@3
            displayName: "Fetch GKE Credentials"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                echo "Fetching credentials for cluster $(GKE_CLUSTER)..."
                gcloud container clusters get-credentials $(GKE_CLUSTER) --region $(GKE_REGION) --project $(PROJECT_ID)
                kubectl config get-contexts
                kubectl config current-context
                kubectl get nodes

          # -----------------------------
          # DEPLOY OR UPDATE APP
          # -----------------------------
          - task: Bash@3
            displayName: "Deploy or Update Image on GKE"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                DEPLOYMENT_NAME=sample-javaapp

                echo "Checking for existing deployment $DEPLOYMENT_NAME..."
                if kubectl -n $(K8S_NAMESPACE) get deployment $DEPLOYMENT_NAME >/dev/null 2>&1; then
                  echo "✅ Deployment exists, updating image..."
                  kubectl -n $(K8S_NAMESPACE) set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$(IMAGE_URI)
                else
                  echo "⚙️  Deployment not found — creating from manifests..."
                  kubectl apply -f k8s/deployment.yaml
                  kubectl apply -f k8s/service.yaml
                fi

                echo "Waiting for rollout to finish..."
                kubectl -n $(K8S_NAMESPACE) rollout status deployment/$DEPLOYMENT_NAME --timeout=300s
                echo "✅ Deployment completed successfully."

          # -----------------------------
          # VERIFY POST DEPLOYMENT
          # -----------------------------
          - task: Bash@3
            displayName: "Post-Deployment Verification"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                echo "Pods in $(K8S_NAMESPACE):"
                kubectl -n $(K8S_NAMESPACE) get pods -o wide
                echo "Services in $(K8S_NAMESPACE):"
                kubectl -n $(K8S_NAMESPACE) get svc -o wide
