trigger: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: java-app-ci
      trigger:
        branches:
          include:
            - azure-pipelines-ci

variables:
  - group: ci-pipeline-vars
  - name: IMAGE_TAG
    value: "226"   # or use $[ resources.pipeline.ciPipeline.runID ]
  - name: IMAGE_URI
    value: "$(LOCATION)-docker.pkg.dev/$(PROJECT_ID)/$(REPOSITORY)/$(IMAGE_NAME):$(IMAGE_TAG)"
  - name: K8S_NAMESPACE
    value: "default"

stages:
  - stage: GCP_DEPLOY
    displayName: "Authenticate & Deploy to GKE"
    jobs:
      - job: Deploy
        displayName: "Deploy image $(IMAGE_URI) to GKE"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: DownloadGcpKey
            displayName: "Download GCP Service Account Key"
            inputs:
              secureFile: "$(SERVICE_ACCOUNT_SECUREFILE)"

          - task: Bash@3
            displayName: "Install Google Cloud SDK and GKE Auth Plugin"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                echo "Installing gcloud CLI..."
                sudo apt-get update -y
                sudo apt-get install -y apt-transport-https ca-certificates gnupg curl lsb-release
                echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
                curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
                sudo apt-get update -y
                sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin
                echo "gcloud version: $(gcloud version | head -n1)"
                echo "gke-gcloud-auth-plugin installed successfully."

          - task: Bash@3
            displayName: "Authenticate to GCP and Configure Docker"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                echo "Authenticating service account..."
                gcloud auth activate-service-account --key-file="$(DownloadGcpKey.secureFilePath)"
                gcloud config set project $(PROJECT_ID)
                gcloud auth configure-docker $(LOCATION)-docker.pkg.dev --quiet
                echo "Auth successful for project: $(PROJECT_ID)"

          - task: Bash@3
            displayName: "Get GKE Credentials"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                echo "Fetching GKE credentials for cluster $(CLUSTER_NAME)..."
                gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(LOCATION) --project $(PROJECT_ID)
                echo "Contexts after authentication:"
                kubectl config get-contexts
                echo "Current context:"
                kubectl config current-context
                echo "Verifying cluster connectivity..."
                kubectl get nodes

          - task: Bash@3
            displayName: "Deploy Image to GKE"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                echo "Deploying image: $(IMAGE_URI)"

                echo "Checking if deployment exists..."
                if kubectl -n $K8S_NAMESPACE get deployment sample-javaapp >/dev/null 2>&1; then
                  echo " Deployment exists. Updating image..."
                  kubectl -n $K8S_NAMESPACE set image deployment/sample-javaapp sample-javaapp=$FULL_IMAGE_NAME
                else
                  echo "Deployment does NOT exist. Creating deployment..."
                  kubectl apply -f k8s/deployment.yaml
                  kubectl apply -f k8s/service.yaml
                fi


                # kubectl -n $(K8S_NAMESPACE) set image deployment/$(IMAGE_NAME) $(IMAGE_NAME)=$(IMAGE_URI)
                # kubectl -n $(K8S_NAMESPACE) rollout status deployment/$(IMAGE_NAME) --timeout=300s
                echo "Deployment completed successfully."

          - task: Bash@3
            displayName: "Post-Deployment Verification"
            inputs:
              targetType: "inline"
              script: |
                set -euo pipefail
                export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                echo "Pods in namespace $(K8S_NAMESPACE):"
                kubectl -n $(K8S_NAMESPACE) get pods -o wide
                echo "Services:"
                kubectl -n $(K8S_NAMESPACE) get svc
