trigger: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: java-app-ci
      trigger:
        branches:
          include:
            - azure-pipelines-ci

variables:
  - group: ci-pipeline-vars
  - name: IMAGE_TAG
    value: "226"    # or use: $[ resources.pipeline.ciPipeline.runID ]
  - name: IMAGE_URI
    value: "$(LOCATION)-docker.pkg.dev/$(PROJECT_ID)/$(REPOSITORY)/$(IMAGE_NAME):$(IMAGE_TAG)"
  - name: K8S_NAMESPACE
    value: 'default'

stages:
  - stage: GCP_AUTH_AND_DEPLOY
    displayName: "Authenticate to GCP and Deploy to GKE"
    jobs:

      # -------------------------------
      # JOB 1: Authenticate and Prepare
      # -------------------------------
      - job: GCP_AUTH
        displayName: "Authenticate to GCP and fetch cluster credentials"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none

          - task: DownloadSecureFile@1
            name: DownloadGcpKey
            displayName: "Download GCP service account key"
            inputs:
              secureFile: '$(SERVICE_ACCOUNT_SECUREFILE)'

          - task: Bash@3
            name: InstallGcloud
            displayName: "Install Google Cloud SDK (if missing)"
            inputs:
              targetType: 'inline'
              script: |
                set -euo pipefail
                if ! command -v gcloud >/dev/null; then
                  echo "Installing google-cloud-sdk..."
                  sudo apt-get update -y
                  sudo apt-get install -y apt-transport-https ca-certificates gnupg curl lsb-release
                  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
                  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
                  sudo apt-get update -y && sudo apt-get install -y google-cloud-sdk
                fi

          - task: Bash@3
            name: GcloudAuth
            displayName: "Authenticate GCP and configure Docker"
            inputs:
              targetType: 'inline'
              script: |
                set -euo pipefail
                echo "Authenticating service account..."
                gcloud auth activate-service-account --key-file="$(DownloadGcpKey.secureFilePath)"
                gcloud config set project $(PROJECT_ID)
                gcloud auth configure-docker $(LOCATION)-docker.pkg.dev --quiet
                echo "Fetching cluster credentials..."
                gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(LOCATION) --project $(PROJECT_ID)
                mkdir -p $(Pipeline.Workspace)/kube
                cp ~/.kube/config $(Pipeline.Workspace)/kube/config
                echo "##vso[task.setvariable variable=KUBECONFIG_PATH]$(Pipeline.Workspace)/kube/config"
                echo "Cluster credentials saved for next job."

          - publish: $(Pipeline.Workspace)/kube
            artifact: kubeconfig

      # -------------------------------
      # JOB 2: Deploy using kubectl
      # -------------------------------
      - job: DEPLOY
        displayName: "Deploy image to GKE"
        dependsOn: GCP_AUTH
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            displayName: "Checkout source code (for manifests)"

          - download: current
            artifact: kubeconfig

          - task: Bash@3
            name: UseKubeConfig
            displayName: "Set kubeconfig for kubectl"
            inputs:
              targetType: 'inline'
              script: |
                set -euo pipefail
                export KUBECONFIG=$(Pipeline.Workspace)/kube/config
                echo "Using kubeconfig at: $KUBECONFIG"

                kubectl config get-contexts

                CONTEXT_NAME=$(kubectl config get-contexts -o name | head -n 1)
                
                if [ -z "$CONTEXT_NAME" ]; then
                  echo "Error: No contexts found in kubeconfig file."
                  exit 1
                fi

                echo "Setting current context to: $CONTEXT_NAME"
                kubectl config use-context "$CONTEXT_NAME"

                kubectl config current-context

          - task: Bash@3
            name: DeployToGKE
            displayName: "Apply deployment with new image"
            inputs:
              targetType: 'inline'
              script: |
                set -euo pipefail
                export KUBECONFIG=$(Pipeline.Workspace)/kube/config
                echo "Deploying image: $(IMAGE_URI)"
                kubectl -n $(K8S_NAMESPACE) set image deployment/$(IMAGE_NAME) $(IMAGE_NAME)=$(IMAGE_URI)
                kubectl -n $(K8S_NAMESPACE) rollout status deployment/$(IMAGE_NAME) --timeout=300s

          - task: Bash@3
            name: PostCheck
            displayName: "Post-deploy sanity checks"
            inputs:
              targetType: 'inline'
              script: |
                set -euo pipefail
                export KUBECONFIG=$(Pipeline.Workspace)/kube/config
                echo "Pods:"
                kubectl -n $(K8S_NAMESPACE) get pods
                echo "Services:"
                kubectl -n $(K8S_NAMESPACE) get svc
