trigger:
  branches:
    include: [main]

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ci-pipeline-vars

stages:
- stage: Build
  displayName: Terraform Build (GAR)
  jobs:
  - job: TerraformBuild
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'gcp'
        command: 'init'
        workingDirectory: 'infra/gar'
        backendServiceConnection: 'GCP-Service-Connection'  # optional
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'gcp'
        command: 'plan'
        workingDirectory: 'infra/gar'
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: TerraformApply
    steps:
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply (GAR)'
      inputs:
        provider: 'gcp'
        command: 'apply'
        workingDirectory: 'infra/gar'
        environmentServiceNameGCP: 'GCP-Service-Connection' # or use secure file auth
        args: '-auto-approve'
